CREATE TABLE `DOC_DOCUMENTO` (
    `DOC_ID` int NOT NULL AUTO_INCREMENT,
    `DOC_NOMBRE` varchar(60) DEFAULT NULL,
    `DOC_CODIGO` varchar(50) DEFAULT NULL,
    `DOC_CONTENIDO` varchar(4000) DEFAULT NULL,
    `DOC_ID_TIPO` int DEFAULT NULL,
    `DOC_ID_PROCESO` int DEFAULT NULL,
    `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`DOC_ID`),
    KEY `fk_doc_id_tipo` (`DOC_ID_TIPO`),
    KEY `fk_doc_id_proceso` (`DOC_ID_PROCESO`),
    CONSTRAINT `fk_doc_id_proceso` FOREIGN KEY (`DOC_ID_PROCESO`) REFERENCES `PRO_PROCESO` (`PRO_ID`),
    CONSTRAINT `fk_doc_id_tipo` FOREIGN KEY (`DOC_ID_TIPO`) REFERENCES `TIP_TIPO_DOC` (`TIP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `PRO_PROCESO` (
    `PRO_ID` int NOT NULL AUTO_INCREMENT,
    `PRO_PREFIJO` varchar(20) DEFAULT NULL,
    `PRO_NOMBRE` varchar(60) DEFAULT NULL,
    `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`PRO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `TIP_TIPO_DOC` (
    `TIP_ID` int NOT NULL AUTO_INCREMENT,
    `TIP_NOMBRE` varchar(60) DEFAULT NULL,
    `TIP_PREFIJO` varchar(20) DEFAULT NULL,
    `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`TIP_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `users` (
    `id` int NOT NULL AUTO_INCREMENT,
    `username` varchar(50) NOT NULL,
    `pass` varchar(255) NOT NULL,
    `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3;
