INSERT INTO `TIP_TIPO_DOC` (`TIP_NOMBRE`, `TIP_PREFIJO`) VALUES
('Instructivo', 'INS'),
('Reporte', 'REP'),
('Factura', 'FAC'),
('Contrato', 'CON'),
('Solicitud', 'SOL'),
('Propuesta', 'PRO'),
('Formulario', 'FOR'),
('Certificado', 'CER'),
('Memorándum', 'MEM'),
('Oferta', 'OFE'),
('Procedimiento', 'PRO'),
('Política', 'POL'),
('Acuerdo', 'ACU'),
('Cotización', 'COT'),
('Memoria', 'MEM'),
('Recibo', 'REC'),
('Orden de Compra', 'ORD'),
('Acta', 'ACT'),
('Presupuesto', 'PRE'),
('Resumen', 'RES');
