INSERT INTO `PRO_PROCESO` (`PRO_PREFIJO`, `PRO_NOMBRE`) VALUES
('ING', 'Ingeniería'),
('PRO', 'Producción'),
('CAL', 'Calidad'),
('LOG', 'Logística'),
('RH', 'Recursos Humanos'),
('VEN', 'Ventas'),
('MAR', 'Marketing'),
('DES', 'Desarrollo'),
('MAN', 'Mantenimiento'),
('FIN', 'Finanzas'),
('LEG', 'Legal'),
('AUD', 'Auditoría'),
('IT', 'IT'),
('SAC', 'Servicio al Cliente'),
('CAP', 'Capacitación'),
('PLA', 'Planificación'),
('INN', 'Innovación'),
('COM', 'Compras'),
('RIS', 'Gestión de Riesgos'),
('DEV', 'Desarrollo');
